// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM5NucScPF_1WFWup60epgijhkZaC1tnQ',
    appId: '1:815198555724:web:e1b2755d51c535dec6aee9',
    messagingSenderId: '815198555724',
    projectId: 'zennect-ea8f0',
    authDomain: 'zennect-ea8f0.firebaseapp.com',
    storageBucket: 'zennect-ea8f0.firebasestorage.app',
    measurementId: 'G-MB3WEKCLSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsPebMMTxhILi16z9Xp3Zwv2DU7jPevvs',
    appId: '1:815198555724:android:765c153097172095c6aee9',
    messagingSenderId: '815198555724',
    projectId: 'zennect-ea8f0',
    storageBucket: 'zennect-ea8f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM0KggCPZbAJKYMZ7brluEGsoFUNoB2pw',
    appId: '1:815198555724:ios:31a8268d9868adaac6aee9',
    messagingSenderId: '815198555724',
    projectId: 'zennect-ea8f0',
    storageBucket: 'zennect-ea8f0.firebasestorage.app',
    iosBundleId: 'com.example.zennect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM0KggCPZbAJKYMZ7brluEGsoFUNoB2pw',
    appId: '1:815198555724:ios:31a8268d9868adaac6aee9',
    messagingSenderId: '815198555724',
    projectId: 'zennect-ea8f0',
    storageBucket: 'zennect-ea8f0.firebasestorage.app',
    iosBundleId: 'com.example.zennect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM5NucScPF_1WFWup60epgijhkZaC1tnQ',
    appId: '1:815198555724:web:ce1d406bbf798dd2c6aee9',
    messagingSenderId: '815198555724',
    projectId: 'zennect-ea8f0',
    authDomain: 'zennect-ea8f0.firebaseapp.com',
    storageBucket: 'zennect-ea8f0.firebasestorage.app',
    measurementId: 'G-DZCRWGJTVE',
  );
}
